### ISSUE TITLE
bug: In link sharing the map is not zoomed to the relevant pin in the other device/browser. 

### ISSUE THREAD

**Issue by sevilayerkan** [acikyazilimagi/musahit-harita-frontend#59] opened 2023-05-24 23:02 UTC
## Bug Definition
In link sharing the map is not zoomed to the relevant pin when in the other device/browser. When a link is opened in other browser, map should be focussed to that area.

-- Please add discord contact information
** discord username: @notdepressedeveloper **

## Bug environment
https://musahit-harita-frontend-git-stage-acikyazilim.vercel.app/?id=45690

## Describe how you are producing the bug step by step

1. Go to https://musahit-harita-frontend-git-stage-acikyazilim.vercel.app/?id=45690
2. Observe the opening page
3. Bug appears

## Expected Behaviour
When a link is opened in other browser, map should be focussed to that area.

## Screen shots
- Shared location
![image](https://github.com/acikkaynak/musahit-harita-frontend/assets/22706692/78996ce2-12e5-4a4b-a1d8-45911e679793)
- Location when shared link is opened
![image](https://github.com/acikkaynak/musahit-harita-frontend/assets/22706692/22005236-9fd3-4883-a8d5-2ab2c1067a34)

**Comment by usirin** [comment] 2023-05-25 06:10
Duplicate of #33

**Closed as completed by usirin** 2023-05-25 06:10 UTC
Labels: bug, p0
