### ISSUE TITLE
bug: There are pins inside lakes

### ISSUE THREAD

**Issue by sevilayerkan** [acikyazilimagi/musahit-harita-frontend#58] opened 2023-05-24 22:52 UTC
## Bug Definition
There are pins in the lakes. There are various pins inside the lakes such as `Tuz Gölü`, `Van Gölü`, `Beyşehir Gölü`. These are i can manage to check so far I think this issue occurs for the other lakes too. 

In addition to that The pins in Lake Van point to the right places, but they do not point to the right place in Salt Lake.

-- Please add discord contact information
** discord username: @notdepressedeveloper **

## Bug environment
https://musahit-harita-frontend-git-stage-acikyazilim.vercel.app/

**Comment by usirin** [comment] 2023-05-24 23:43
Duplicate of #45

**Closed as not planned by usirin** 2023-05-24 23:43 UTC
Labels: bug
