### ISSUE TITLE
feat: Page: Pin Detay

### ISSUE THREAD

**Issue by bltMustafa** [acikyazilimagi/musahit-harita-frontend#27] opened 2023-05-23 00:47 UTC
On Click of pinned neighbourhoud display modal

Implement Social Share button
Implement "Gönüllü Ol" button - opens a form

The drawer info will be finalized - TBC

![pindetay](https://github.com/acikkaynak/musahit-harita-frontend/assets/92399033/748177cf-d224-4692-b4db-81eaec6f4501)

** discord username: `@Mustafa Bolat#4560 `**

**Comment by usirin** [comment] 2023-05-24 00:43
Duplicate of #38

**Closed as not planned by usirin** 2023-05-24 00:43 UTC
Labels: enhancement
